In [46]:
print("Jupyter Working")

Jupyter Working

In [47]:
import pandas as pd

df = pd.read_csv("../Excel/Cleaned_Data.csv")

df.head()

,Order_ID,Order_Date,Promised_Delivery_Date,Actual_Delivery_Date,City,Zone,Warehouse_ID,Delivery_Agent_ID,Vendor,Product_Category,...,Delay_Days,Delay_Category,Is_Delayed,Delay_Reason,SLA_Breached,Delivery_Attempts,Month,Quarter,Is_Festive_Season,Is_Monsoon_Season
0,ORD100000,27-02-2024,01-03-2024,03-03-2024,Surat,West,WH_SRT_01,AGT_0008,BlueDart,Beauty,...,2,Minor Delay,Yes,Wrong Address,No,1,February,Q1,No,No
1,ORD100001,21-04-2024,28-04-2024,30-04-2024,Delhi,North,WH_DEL_01,AGT_0109,Ekart,Electronics,...,2,Minor Delay,Yes,Warehouse Processing Delay,No,1,April,Q2,No,No
2,ORD100002,22-05-2024,25-05-2024,29-05-2024,Kolkata,East,WH_KOL_01,AGT_0138,Dunzo,Electronics,...,4,Moderate Delay,Yes,Wrong Address,Yes,1,May,Q2,No,No
3,ORD100003,12-07-2024,15-07-2024,15-07-2024,Delhi,North,WH_DEL_01,AGT_0075,XpressBees,Electronics,...,0,On Time,No,NaN,No,1,July,Q3,No,Yes
4,ORD100004,29-04-2024,02-05-2024,02-05-2024,Delhi,North,WH_DEL_01,AGT_0044,Delhivery,Books,...,0,On Time,No,NaN,No,1,April,Q2,No,No

In [48]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5200 entries, 0 to 5199
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Order_ID                5200 non-null   object
 1   Order_Date              5200 non-null   object
 2   Promised_Delivery_Date  5200 non-null   object
 3   Actual_Delivery_Date    5200 non-null   object
 4   City                    5200 non-null   object
 5   Zone                    5200 non-null   object
 6   Warehouse_ID            5200 non-null   object
 7   Delivery_Agent_ID       5200 non-null   object
 8   Vendor                  5200 non-null   object
 9   Product_Category        5200 non-null   object
 10  Order_Value_INR         5200 non-null   float64
 11  Payment_Mode            5200 non-null   object
 12  Promised_Delivery_Days  5200 non-null   int64
 13  Actual_Delivery_Days    5200 non-null   int64
 14  Delay_Days              5200 non-null   int64
 15  Delay_Category          5200 non-null   object
 16  Is_Delayed              5200 non-null   object
 17  Delay_Reason            2003 non-null   object
 18  SLA_Breached            5200 non-null   object
 19  Delivery_Attempts       5200 non-null   int64
 20  Month                   5200 non-null   object
 21  Quarter                 5200 non-null   object
 22  Is_Festive_Season       5200 non-null   object
 23  Is_Monsoon_Season       5200 non-null   object
dtypes: float64(1), int64(4), object(19)
memory usage: 975.1+ KB

In [49]:
df.head()

,Order_ID,Order_Date,Promised_Delivery_Date,Actual_Delivery_Date,City,Zone,Warehouse_ID,Delivery_Agent_ID,Vendor,Product_Category,...,Delay_Days,Delay_Category,Is_Delayed,Delay_Reason,SLA_Breached,Delivery_Attempts,Month,Quarter,Is_Festive_Season,Is_Monsoon_Season
0,ORD100000,27-02-2024,01-03-2024,03-03-2024,Surat,West,WH_SRT_01,AGT_0008,BlueDart,Beauty,...,2,Minor Delay,Yes,Wrong Address,No,1,February,Q1,No,No
1,ORD100001,21-04-2024,28-04-2024,30-04-2024,Delhi,North,WH_DEL_01,AGT_0109,Ekart,Electronics,...,2,Minor Delay,Yes,Warehouse Processing Delay,No,1,April,Q2,No,No
2,ORD100002,22-05-2024,25-05-2024,29-05-2024,Kolkata,East,WH_KOL_01,AGT_0138,Dunzo,Electronics,...,4,Moderate Delay,Yes,Wrong Address,Yes,1,May,Q2,No,No
3,ORD100003,12-07-2024,15-07-2024,15-07-2024,Delhi,North,WH_DEL_01,AGT_0075,XpressBees,Electronics,...,0,On Time,No,NaN,No,1,July,Q3,No,Yes
4,ORD100004,29-04-2024,02-05-2024,02-05-2024,Delhi,North,WH_DEL_01,AGT_0044,Delhivery,Books,...,0,On Time,No,NaN,No,1,April,Q2,No,No

In [50]:
df.isnull().sum()

Order_ID                     0
Order_Date                   0
Promised_Delivery_Date       0
Actual_Delivery_Date         0
City                         0
Zone                         0
Warehouse_ID                 0
Delivery_Agent_ID            0
Vendor                       0
Product_Category             0
Order_Value_INR              0
Payment_Mode                 0
Promised_Delivery_Days       0
Actual_Delivery_Days         0
Delay_Days                   0
Delay_Category               0
Is_Delayed                   0
Delay_Reason              3197
SLA_Breached                 0
Delivery_Attempts            0
Month                        0
Quarter                      0
Is_Festive_Season            0
Is_Monsoon_Season            0
dtype: int64

In [51]:
df.shape

(5200, 24)

In [52]:
df.columns

Index(['Order_ID', 'Order_Date', 'Promised_Delivery_Date',
       'Actual_Delivery_Date', 'City', 'Zone', 'Warehouse_ID',
       'Delivery_Agent_ID', 'Vendor', 'Product_Category', 'Order_Value_INR',
       'Payment_Mode', 'Promised_Delivery_Days', 'Actual_Delivery_Days',
       'Delay_Days', 'Delay_Category', 'Is_Delayed', 'Delay_Reason',
       'SLA_Breached', 'Delivery_Attempts', 'Month', 'Quarter',
       'Is_Festive_Season', 'Is_Monsoon_Season'],
      dtype='object')

In [53]:
df["City"].value_counts()

City
Surat        373
Mumbai       370
Bhopal       368
Chennai      357
Indore       355
Delhi        352
Lucknow      352
Kolkata      350
Nagpur       349
Bangalore    340
Pune         337
Patna        329
Ahmedabad    329
Jaipur       326
Hyderabad    313
Name: count, dtype: int64

In [54]:
df["Vendor"].value_counts()

Vendor
Ecom Express    681
Dunzo           669
Ekart           668
DTDC            644
XpressBees      639
Shadowfax       635
BlueDart        632
Delhivery       632
Name: count, dtype: int64

In [55]:
df["Delay_Reason"].value_counts()

Delay_Reason
Traffic Congestion            277
Warehouse Processing Delay    257
Weather Conditions            255
Wrong Address                 248
Route Optimization Failure    248
Customer Unavailable          242
High Order Volume             241
Vehicle Breakdown             235
Name: count, dtype: int64